spring:
  security:
    oauth2:
      client:
        registration:
         github:
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          scope:
           - user:email
           - read:user
